import fs from 'node:fs';
import { chromium } from 'playwright';
const dir = process.env.OUT || 'screenshots';
fs.mkdirSync(dir, { recursive: true });
const b = await chromium.launch({ executablePath: process.env.CHROME || '/opt/pw-browsers/chromium' });
const ctx = await b.newContext({ viewport: { width: 420, height: 820 }, deviceScaleFactor: 2, locale: 'nl-NL', geolocation: { latitude: 52.2166, longitude: 4.5934 }, permissions: ['geolocation'] });
const p = await ctx.newPage();
const errors = [];
p.on('pageerror', e => errors.push('pageerror: ' + e.message));
p.on('console', m => { if (m.type() === 'error' && !m.text().includes('ERR_')) errors.push('console: ' + m.text()); });
const shot = (n) => p.screenshot({ path: `${dir}/${n}.png` });
await p.goto('http://127.0.0.1:4173/');
await p.waitForTimeout(2500);
await shot('01_start');
await p.fill('input[aria-label="A"]', 'Kaag'); await p.waitForTimeout(500); await p.click('.search-results li >> nth=0');
await p.fill('input[aria-label="B"]', 'Amsterdam'); await p.waitForTimeout(500); await p.click('.search-results li >> nth=0');
await p.waitForTimeout(1500);
await shot('02_route');
await p.click('text=Dagindeling'); await p.waitForTimeout(600); await shot('03_stages');
await p.click('text=Aanleggen'); await p.waitForTimeout(400); await shot('04_moor');
await p.click('text=Route'); await p.waitForTimeout(400); await shot('05_ops');
await p.click('text=Start navigatie'); await p.waitForTimeout(2000); await shot('06_nav');
await p.click('text=Stop'); await p.waitForTimeout(500);
await p.click('.tabbar button:has-text("Leren")'); await p.waitForTimeout(500); await shot('07_learn');
await p.click('.card >> nth=0'); await p.waitForTimeout(500); await shot('08_lesson');
await p.click('.tabbar button:has-text("Aan boord")'); await p.waitForTimeout(500);
await p.click('text=Checklists'); await p.waitForTimeout(300); await shot('09_check');
await p.click('text=Instellingen'); await p.waitForTimeout(300); await shot('10_settings');
await p.click('.tabbar button:has-text("Tochten")'); await p.waitForTimeout(300); await shot('11_trips');
console.log(JSON.stringify(errors, null, 1));
await b.close();
